/**
 * @file src/tasks/ButtonTask.h
 * @author DvidMakesThings - David Sipos
 *
 * @defgroup tasks Tasks
 * @brief General task implementations for ENERGIS PDU firmware.
 * @{
 *
 * @defgroup tasks01 1. Button Task
 * @ingroup tasks
 * @brief Button input handling with debouncing and selection window management.
 * @{
 *
 * @version 1.0.1
 * @date 2025-11-08
 *
 * @details
 * This module implements a FreeRTOS task for handling physical button inputs on the PDU.
 * It provides debounced button reading, selection window management with visual feedback,
 * and power state control through button combinations.
 *
 * Key Features:
 * - Polls PLUS, MINUS, SET, and PWR button GPIOs at configurable intervals
 * - Software debouncing with configurable timing thresholds
 * - Distinction between short and long press events for SET and PWR buttons
 * - Selection window with timeout and LED blinking feedback
 * - Event queue for inter-task communication
 * - Power management integration for standby mode control
 *
 * Button Behavior:
 * - PLUS: Move selection right (wraps around), only when window is active
 * - MINUS: Move selection left (wraps around), only when window is active
 * - SET (short): Toggle selected relay output, opens window if closed
 * - SET (long): Clear error/warning logs and fault LED
 * - PWR (long): Enter standby mode from normal operation
 * - PWR (short): Exit standby mode when in standby
 *
 * The selection window provides visual feedback via blinking LEDs and automatically
 * closes after a configurable timeout period. The task operates without interrupts,
 * using polling to maintain predictable real-time behavior.
 *
 * @project ENERGIS - The Managed PDU Project for 10-Inch Rack
 * @github https://github.com/DvidMakesThings/HW_10-In-Rack_PDU
 */

#ifndef ENERGIS_BUTTONTASK_H
#define ENERGIS_BUTTONTASK_H

#include "../CONFIG.h"

/**
 * @name Configuration Parameters
 * @brief Tunable timing for scanning, blink, window, and readiness.
 * @{
 */

/**
 * @brief Button scanning period in milliseconds.
 *
 * Defines how frequently the task polls button GPIO states. Lower values
 * provide faster response but increase CPU usage. Typical range: 5-20ms.
 */
#ifndef BTN_SCAN_PERIOD_MS
#define BTN_SCAN_PERIOD_MS 10u
#endif

/**
 * @brief Selection LED blink period in milliseconds.
 *
 * Controls the on/off cycle time for the selection indicator LED during
 * the active selection window. Must be long enough to be visible to users.
 */
#ifndef SELECT_BLINK_MS
#define SELECT_BLINK_MS 250u
#endif

/**
 * @brief Selection window timeout in milliseconds.
 *
 * Duration for which the selection window remains open after the last button
 * interaction. After timeout, LEDs turn off and window closes automatically.
 */
#ifndef SELECT_WINDOW_MS
#define SELECT_WINDOW_MS 10000u
#endif

/**
 * @brief Storage task readiness timeout in milliseconds.
 *
 * Maximum time to wait for StorageTask initialization during bring-up sequence.
 * ButtonTask initialization fails if storage is not ready within this period.
 */
#ifndef BUTTON_WAIT_STORAGE_READY_MS
#define BUTTON_WAIT_STORAGE_READY_MS 5000u
#endif
/** @} */

/**
 * @enum btn_event_kind_t
 * @brief Button event types published to `q_btn`.
 * @ingroup tasks01
 * @details
 * - Edge events: debounced PLUS/MINUS press and release transitions.
 * - Press events: SET short/long press determined by duration thresholds.
 * - Events are generated by `ButtonTask` and consumed by subscribers via the queue.
 */
typedef enum {
    /**
     * @name Edge Events
     * @brief Debounced GPIO transitions for PLUS and MINUS.
     * @{
     */
    BTN_EV_PLUS_FALL = 1u,  /**< PLUS button pressed (debounced falling edge detected). */
    BTN_EV_PLUS_RISE = 2u,  /**< PLUS button released (debounced rising edge detected). */
    BTN_EV_MINUS_FALL = 3u, /**< MINUS button pressed (debounced falling edge detected). */
    BTN_EV_MINUS_RISE = 4u, /**< MINUS button released (debounced rising edge detected). */
    /** @} */

    /**
     * @name Press Events
     * @brief SET button short/long press classification.
     * @{
     */
    BTN_EV_SET_SHORT = 5u, /**< SET button short press confirmed on release. */
    BTN_EV_SET_LONG = 6u   /**< SET button long press confirmed while held down. */
    /** @} */
} btn_event_kind_t;

/**
 * @struct btn_event_t
 * @brief Button event message published to the queue.
 * @ingroup tasks01
 * @details
 * Contains the event kind, timestamp, and current selection index. Produced
 * by `ButtonTask` and consumed by subscribers from `q_btn`.
 */
typedef struct {
    btn_event_kind_t kind; /**< Type of button event that occurred. */
    uint32_t t_ms;         /**< Event timestamp in milliseconds since boot. */
    uint8_t sel;           /**< Currently selected output channel (0-7). */
} btn_event_t;

/**
 * @brief Global queue for button event distribution.
 * @ingroup tasks01
 * @details
 * FreeRTOS queue handle used by `ButtonTask` to publish button events. Other
 * tasks subscribe to this queue to receive notifications. The queue is created
 * during `ButtonTask_Init()` and remains valid throughout runtime.
 */
extern QueueHandle_t q_btn;

/**
 * @brief Initialize and start the button handling task.
 *
 * Creates the ButtonTask FreeRTOS task, initializes button GPIOs, sets up the
 * event queue, and configures the LED blink timer. Implements deterministic
 * initialization with storage readiness gate.
 *
 * Initialization sequence:
 * 1. Initializes button GPIO pins with pull-ups
 * 2. Waits for StorageTask readiness (with timeout)
 * 3. Initializes power manager
 * 4. Creates button event queue (32 events deep)
 * 5. Creates and starts LED blink timer
 * 6. Spawns ButtonTask with configured priority
 *
 * @param enable Set true to initialize and start task, false to skip initialization
 *               deterministically without side effects.
 *
 * @return pdPASS on successful initialization or when skipped (enable=false).
 * @return pdFAIL if initialization fails (timeout, queue creation, task creation).
 *
 * @note This function blocks until StorageTask becomes ready or timeout occurs.
 * @note Logs error codes to error logger on failure.
 */
BaseType_t ButtonTask_Init(bool enable);

/**
 * @brief Query button task readiness status.
 *
 * Provides a thread-safe method to check whether ButtonTask has completed
 * initialization successfully. Used for deterministic boot sequencing to
 * ensure proper task dependency ordering.
 *
 * @return true if ButtonTask_Init(true) completed successfully and task is running.
 * @return false if ButtonTask_Init() was not called, called with enable=false,
 *         or initialization failed.
 *
 * @note This function is safe to call from any task context.
 */
bool Button_IsReady(void);

#endif /* ENERGIS_BUTTONTASK_H */

/** @} */
/** @} */